# Generated by Django 6.0 on 2026-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('account', 'Regular Account'), ('investment', 'Investment'), ('card', 'Credit Card')], default='account', max_length=50),
        ),
    ]
